# Generated by Django 3.2.14 on 2022-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20220804_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Budder',
            field=models.BooleanField(default=False, verbose_name='Is Bidder'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Is seller'),
        ),
    ]
