# Generated by Django 3.2.14 on 2022-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
